<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>.</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="BatteryTestingSystem.Tests" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="logs\**" />
    <Compile Remove="Security\**" />
    <Compile Remove="BatteryTestingSystem.Tests\**" />
    <Content Remove="logs\**" />
    <Content Remove="Security\**" />
    <Content Remove="BatteryTestingSystem.Tests\**" />
    <EmbeddedResource Remove="logs\**" />
    <EmbeddedResource Remove="Security\**" />
    <EmbeddedResource Remove="BatteryTestingSystem.Tests\**" />
    <None Remove="logs\**" />
    <None Remove="Security\**" />
    <None Remove="BatteryTestingSystem.Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Components\UI\Dashboard\RealTimeView.razor" />
    <Content Remove="wwwroot\js\bms-export.js" />
    <Content Remove="wwwroot\js\download.js" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Components\UI\DynamicTable\DynamicTableExample.md" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Components\UI\PageHeader\" />
    <Folder Include="Migrations\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Components\UI\Dashboard\ColorsSettings.razor" />
    <None Include="wwwroot\js\bms-export.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="wwwroot\js\download.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="wwwroot\js\highcharts\bms-chart.js" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Blazicons.Lucide" Version="1.13.35" />
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.2.0" />
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.23" />
    <PackageReference Include="Hangfire.Core" Version="1.8.23" />
    <PackageReference Include="Hangfire.Storage.SQLite" Version="0.4.3" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    <PackageReference Include="ModelContextProtocol.AspNetCore" Version="1.2.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="5.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlcipher" Version="2.1.11" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="UAParser" Version="3.1.47" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="Components\UI\DataViewer\BmsDashboard.razor">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
    <Content Update="HardwareSimulator\config.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Update="Components\UI\DataViewer\bms-export.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
